### ISSUE TITLE
Add a proper functional replacement for the replaced FXAA

### ISSUE THREAD

**Issue by SirYodaJedi** [tlaik/neptastic#9]
I'm not certain the original implementation could even be considered anti-aliasing, but it does do a little bit of hiding the jaggies. At the same time, I like how your hook crispen up the full game image. Despite this, it doesn't really replace the "anti-aliasing" insomuch as it removes it altogether. It's possible to clean up some stairstepping by setting 2.0x resolution, but due to the bicubic scaling used it isn't the most effective, and setting it to any higher than 2.0x actually introduces *more* aliasing.

Ideally, some form of MSAA or Halton SSAA would be preferred, but given the artstyle I think SMAA or a better FXAA would be sufficient at cleaning up what is left in the downscaled image. Sure, I could force those through my GPU or something like ReShade, but those would negatively impact the video quality of the visual novel segments, unlike a theoretical implementation in this wrapper hook.

**Comment by tlaik** [comment]
I didn't really consider looking for and testing new AA shaders, since the 2x downscale seems to be doing a good enough job for most people. If you suspect that this or that AA type can give significantly better results, you can try it out yourself - look at how certain shaders are already replaced in nep_hooks.cpp inside the cgCreateProgram hook. You'd want to work with the part which overrides the combined FXAA/Bloom shader, and replace its code with your own solution.
